packages:
  - "packages/**/*"
allowBuilds:
  "@swc/core": true
  unrs-resolver: true
overrides:
  abab: npm:@nolyfill/abab@^1.0.44
  array-buffer-byte-length: npm:@nolyfill/array-buffer-byte-length@^1.0.44
  array-flatten: npm:@nolyfill/array-flatten@^1.0.44
  array-includes: npm:@nolyfill/array-includes@^1.0.44
  array.from: npm:@nolyfill/array.from@^1.0.44
  array.of: npm:@nolyfill/array.of@^1.0.44
  array.prototype.at: npm:@nolyfill/array.prototype.at@^1.0.44
  array.prototype.every: npm:@nolyfill/array.prototype.every@^1.0.44
  array.prototype.find: npm:@nolyfill/array.prototype.find@^1.0.44
  array.prototype.findlast: npm:@nolyfill/array.prototype.findlast@^1.0.44
  array.prototype.findlastindex: npm:@nolyfill/array.prototype.findlastindex@^1.0.44
  array.prototype.flat: npm:@nolyfill/array.prototype.flat@^1.0.44
  array.prototype.flatmap: npm:@nolyfill/array.prototype.flatmap@^1.0.44
  array.prototype.foreach: npm:@nolyfill/array.prototype.foreach@^1.0.44
  array.prototype.reduce: npm:@nolyfill/array.prototype.reduce@^1.0.44
  array.prototype.toreversed: npm:@nolyfill/array.prototype.toreversed@^1.0.44
  array.prototype.tosorted: npm:@nolyfill/array.prototype.tosorted@^1.0.44
  arraybuffer.prototype.slice: npm:@nolyfill/arraybuffer.prototype.slice@^1.0.44
  assert: npm:@nolyfill/assert@^1.0.26
  asynciterator.prototype: npm:@nolyfill/asynciterator.prototype@^1.0.44
  available-typed-arrays: npm:@nolyfill/available-typed-arrays@^1.0.44
  deep-equal: npm:@nolyfill/deep-equal@^1.0.44
  deep-equal-json: npm:@nolyfill/deep-equal-json@^1.0.44
  define-properties: npm:@nolyfill/define-properties@^1.0.44
  es-aggregate-error: npm:@nolyfill/es-aggregate-error@^1.0.44
  es-iterator-helpers: npm:@nolyfill/es-iterator-helpers@^1.0.21
  es-set-tostringtag: npm:@nolyfill/es-set-tostringtag@^1.0.44
  es6-object-assign: npm:@nolyfill/es6-object-assign@^1.0.44
  function-bind: npm:@nolyfill/function-bind@^1.0.21
  function.prototype.name: npm:@nolyfill/function.prototype.name@^1.0.44
  get-symbol-description: npm:@nolyfill/get-symbol-description@^1.0.44
  globalthis: npm:@nolyfill/globalthis@^1.0.44
  gopd: npm:@nolyfill/gopd@^1.0.44
  harmony-reflect: npm:@nolyfill/harmony-reflect@^1.0.44
  has: npm:@nolyfill/has@^1.0.44
  has-property-descriptors: npm:@nolyfill/has-property-descriptors@^1.0.44
  has-proto: npm:@nolyfill/has-proto@^1.0.44
  has-symbols: npm:@nolyfill/has-symbols@^1.0.21
  has-tostringtag: npm:@nolyfill/has-tostringtag@^1.0.21
  hasown: npm:@nolyfill/hasown@^1.0.44
  internal-slot: npm:@nolyfill/internal-slot@^1.0.44
  is-arguments: npm:@nolyfill/is-arguments@^1.0.44
  is-array-buffer: npm:@nolyfill/is-array-buffer@^1.0.44
  is-core-module: npm:@nolyfill/is-core-module@^1.0.39
  is-date-object: npm:@nolyfill/is-date-object@^1.0.44
  is-generator-function: npm:@nolyfill/is-generator-function@^1.0.44
  is-nan: npm:@nolyfill/is-nan@^1.0.44
  is-regex: npm:@nolyfill/is-regex@^1.0.44
  is-shared-array-buffer: npm:@nolyfill/is-shared-array-buffer@^1.0.44
  is-string: npm:@nolyfill/is-string@^1.0.44
  is-symbol: npm:@nolyfill/is-symbol@^1.0.44
  is-typed-array: npm:@nolyfill/is-typed-array@^1.0.44
  is-weakref: npm:@nolyfill/is-weakref@^1.0.44
  isarray: npm:@nolyfill/isarray@^1.0.44
  iterator.prototype: npm:@nolyfill/iterator.prototype@^1.0.44
  json-stable-stringify: npm:@nolyfill/json-stable-stringify@^1.0.44
  jsonify: npm:@nolyfill/jsonify@^1.0.44
  number-is-nan: npm:@nolyfill/number-is-nan@^1.0.44
  object-is: npm:@nolyfill/object-is@^1.0.44
  object-keys: npm:@nolyfill/object-keys@^1.0.44
  object.assign: npm:@nolyfill/object.assign@^1.0.44
  object.entries: npm:@nolyfill/object.entries@^1.0.44
  object.fromentries: npm:@nolyfill/object.fromentries@^1.0.44
  object.getownpropertydescriptors: npm:@nolyfill/object.getownpropertydescriptors@^1.0.44
  object.groupby: npm:@nolyfill/object.groupby@^1.0.44
  object.hasown: npm:@nolyfill/object.hasown@^1.0.44
  object.values: npm:@nolyfill/object.values@^1.0.44
  promise.allsettled: npm:@nolyfill/promise.allsettled@^1.0.44
  promise.any: npm:@nolyfill/promise.any@^1.0.44
  reflect.getprototypeof: npm:@nolyfill/reflect.getprototypeof@^1.0.44
  reflect.ownkeys: npm:@nolyfill/reflect.ownkeys@^1.0.44
  regexp.prototype.flags: npm:@nolyfill/regexp.prototype.flags@^1.0.44
  safe-array-concat: npm:@nolyfill/safe-array-concat@^1.0.44
  safe-buffer: npm:@nolyfill/safe-buffer@^1.0.44
  safe-regex-test: npm:@nolyfill/safe-regex-test@^1.0.44
  safer-buffer: npm:@nolyfill/safer-buffer@^1.0.44
  set-function-length: npm:@nolyfill/set-function-length@^1.0.25
  side-channel: npm:@nolyfill/side-channel@^1.0.44
  string.prototype.at: npm:@nolyfill/string.prototype.at@^1.0.44
  string.prototype.codepointat: npm:@nolyfill/string.prototype.codepointat@^1.0.44
  string.prototype.includes: npm:@nolyfill/string.prototype.includes@^1.0.44
  string.prototype.matchall: npm:@nolyfill/string.prototype.matchall@^1.0.44
  string.prototype.padend: npm:@nolyfill/string.prototype.padend@^1.0.44
  string.prototype.padstart: npm:@nolyfill/string.prototype.padstart@^1.0.44
  string.prototype.repeat: npm:@nolyfill/string.prototype.repeat@^1.0.44
  string.prototype.replaceall: npm:@nolyfill/string.prototype.replaceall@^1.0.44
  string.prototype.split: npm:@nolyfill/string.prototype.split@^1.0.44
  string.prototype.startswith: npm:@nolyfill/string.prototype.startswith@^1.0.44
  string.prototype.trim: npm:@nolyfill/string.prototype.trim@^1.0.44
  string.prototype.trimend: npm:@nolyfill/string.prototype.trimend@^1.0.44
  string.prototype.trimleft: npm:@nolyfill/string.prototype.trimleft@^1.0.44
  string.prototype.trimright: npm:@nolyfill/string.prototype.trimright@^1.0.44
  string.prototype.trimstart: npm:@nolyfill/string.prototype.trimstart@^1.0.44
  typed-array-buffer: npm:@nolyfill/typed-array-buffer@^1.0.44
  typed-array-byte-length: npm:@nolyfill/typed-array-byte-length@^1.0.44
  typed-array-byte-offset: npm:@nolyfill/typed-array-byte-offset@^1.0.44
  typed-array-length: npm:@nolyfill/typed-array-length@^1.0.44
  typedarray: npm:@nolyfill/typedarray@^1.0.44
  typedarray.prototype.slice: npm:@nolyfill/typedarray.prototype.slice@^1.0.44
  unbox-primitive: npm:@nolyfill/unbox-primitive@^1.0.44
  util.promisify: npm:@nolyfill/util.promisify@^1.0.44
  which-boxed-primitive: npm:@nolyfill/which-boxed-primitive@^1.0.44
  which-typed-array: npm:@nolyfill/which-typed-array@^1.0.44
patchedDependencies:
  assert@2.1.0: patches/assert@2.1.0.patch
